### PR TITLE
Mpgs Module for Prestashop v 1.1.0

### PR DESCRIPTION
**Pull request by kristjan-h**

### CODE REVIEW

**Comment by kk98** [comment]
Hi, I've tried the module, i am unable to install the module in prestashop 1.7.1.1

image

Above is the error image which i am facing.

Secondly, i've observed that config.xml file is missing from the module, which has configurations.

**Comment by kristjan-h** [comment]
Thanks for the feedback @kk98 

1. Error message says that module zip is not valid, from where was the zip file taken from?

2. According to Prestashop, `config.xml` is a configuration cache file, which is automatically created during the module's installation, it should not be included with the module itself. See https://devdocs.prestashop.com/1.7/modules/creation/#installing-the-module

**Comment by kk98** [comment]
Thanks for your prompt response @OnTapKristjan .

i have downloaded the zip file from your release repository. 

https://github.com/Mastercard-Gateway/gateway-prestashop-module/releases

Can you help me, in installing the module so that i can test it on my prestashop 1.7.1.1

I have also attached the zip, which i am trying to install.

[gateway-prestashop-module-1.0.0.zip](https://github.com/Mastercard-Gateway/gateway-prestashop-module/files/4373936/gateway-prestashop-module-1.0.0.zip)

**Comment by kristjan-h** [comment]
Probably downloaded an old source file.

Here is a correct one attached
[prestashop-mastercard.zip](https://github.com/Mastercard-Gateway/gateway-prestashop-module/files/4373956/prestashop-mastercard.zip)

**Comment by kk98** [comment]
Thanks, for the updated one. It is now installed successfully.

But i after the installation in configuration when i enter the API Password & Webhook Secret and click on save button, then API Password & Webhook Secret disappeared and won't saved.

image

**Comment by kk98** [comment]
Hi @OnTapKristjan would you be able to help me regarding the issue of configurations not saving like API Password and Webhook Secret.

These values are coming from prestashop configuration, but API Password & Webhook Secret are not in Configurations. 

Can you please help me out here?

**Comment by jk00000** [comment]
Hi kk98.
This last issue is not something on Tap can assist with, it appears to be an API credential problem, please contact your payment gateway provider.

**Review by mdhilwan — COMMENTED** [review]
in `gateway.php`, might want to consider adding more_entropy to `true` in the method `check3dsEnrollment()`:
```
$threeDSecureId = uniqid(sprintf('3DS-'), true);
```
Insecure usage of `uniqid()`

**Comment by kristjan-h** [comment]
> in `gateway.php`, might want to consider adding more_entropy to `true` in the method `check3dsEnrollment()`:
> 
> ```
> $threeDSecureId = uniqid(sprintf('3DS-'), true);
> ```
> 
> Insecure usage of `uniqid()`

more_entropy is now used in uniqid function call

**Review by mdhilwan — APPROVED** [review]
Reviewed

**Comment by Kingsleynhangumele225** [comment]
Hi

im new in this MPGS integration with Prestashop, however, I´ve managed to integrate with prestashop, but i´m having a problem when doing my tests, my transactions don´t have Order Reference ( On my MPGS site)

Can someone please help me understand whats happening and how i can fix?

**Pull request merged**
